[project]
name = "findpython"
version = "0.1.1"
description = "A utility to find python versions on your system"
authors = [
    {name = "Frost Ming", email = "mianghong@gmail.com"},
]
dependencies = [
    "packaging>=20",
]
requires-python = ">=3.7"
license = {text = "MIT"}
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[project.urls]
Homepage = "https://github.com/frostming/findpython"

[project.scripts]
findpython = "findpython.__main__:main"

[tool.pdm]
package-dir = "src"

[tool.pdm.dev-dependencies]
dev = [
    "vendoring; python_version >= '3.8'"
]

tests = ["pytest"]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.black]
line-length = 90
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | src/pythonfinder/_vendor
)
'''

[tool.isort]
profile = "black"
atomic = true
filter_files = true
known_first_party = ["findpython"]

[tool.vendoring]
destination = "src/findpython/_vendor/"
requirements = "src/findpython/_vendor/vendor.txt"
namespace = "findpython._vendor"

protected-files = ["__init__.py", "README.md", "vendor.txt"]
